Repository MichaelMrt/ChessPHP, pull requests merged in 2024-02, with the labels that each got.

#1 Building core logic structure of the project
  src/chesspieces/chess_piece.php
  src/controller.php
  src/logic/chesspieces/chess_piece.php
  src/logic/chesspieces/pawn.php
  src/logic/logic.php
  src/style.css
Labels: enhancement

#9 added boardcolors through CSS-class and usage of modulo operator
  src/logic/logic.php
  src/style.css
Labels: enhancement

#10 Combined x and y inputs to one
  src/logic/logic.php
Labels: enhancement

#12 Styled inputs, submit button and changed font
  src/style.css
Labels: enhancement

#13 Implemented check_move_legal-function for Pawn
  src/logic/chesspieces/chess_piece.php
  src/logic/chesspieces/pawn.php
  src/logic/logic.php
Labels: enhancement

#18 Move json serialize and added type var
  src/logic/chesspieces/chess_piece.php
  src/logic/chesspieces/pawn.php
Labels: enhancement

#19 formatted check_move_legal func
  src/logic/chesspieces/pawn.php
Labels: low priority

#29 Restructure to make ui work
  src/chessgame.php
  src/controller.php
  src/logic/chesspieces/chess_piece.php
  src/logic/chesspieces/pawn.php
  src/logic/logic.php
  src/ui/ui.php
Labels: High priority
